# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: books.proto for package 'bookshelf'

require 'grpc'
require 'books_pb'

module Bookshelf
  module BookService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bookshelf.BookService'

      rpc :ListBooks, ::Bookshelf::ListBooksRequest, ::Bookshelf::ListBooksResponse
      rpc :GetBook, ::Bookshelf::GetBookRequest, ::Bookshelf::BookResponse
      rpc :CreateBook, ::Bookshelf::CreateBookRequest, ::Bookshelf::BookResponse
      rpc :CreateAuthor, ::Bookshelf::CreateAuthorRequest, ::Bookshelf::AuthorResponse
    end

    Stub = Service.rpc_stub_class
  end
end
