# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x62ooks.proto\x12\tbookshelf\"\x12\n\x10ListBooksRequest\":\n\x11ListBooksResponse\x12%\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x16.bookshelf.BookMessage\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\x11\x43reateBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x16\n\x0epublished_year\x18\x02 \x01(\x05\x12\x11\n\tauthor_id\x18\x03 \x01(\t\"0\n\x13\x43reateAuthorRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x62io\x18\x02 \x01(\t\"j\n\x0b\x42ookMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x16\n\x0epublished_year\x18\x03 \x01(\x05\x12(\n\x06\x61uthor\x18\x04 \x01(\x0b\x32\x18.bookshelf.AuthorMessage\"6\n\rAuthorMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\"D\n\x0c\x42ookResponse\x12$\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x16.bookshelf.BookMessage\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t\"J\n\x0e\x41uthorResponse\x12(\n\x06\x61uthor\x18\x01 \x01(\x0b\x32\x18.bookshelf.AuthorMessage\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t2\xa4\x02\n\x0b\x42ookService\x12\x46\n\tListBooks\x12\x1b.bookshelf.ListBooksRequest\x1a\x1c.bookshelf.ListBooksResponse\x12=\n\x07GetBook\x12\x19.bookshelf.GetBookRequest\x1a\x17.bookshelf.BookResponse\x12\x43\n\nCreateBook\x12\x1c.bookshelf.CreateBookRequest\x1a\x17.bookshelf.BookResponse\x12I\n\x0c\x43reateAuthor\x12\x1e.bookshelf.CreateAuthorRequest\x1a\x19.bookshelf.AuthorResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bookshelf
  ListBooksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.ListBooksRequest").msgclass
  ListBooksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.ListBooksResponse").msgclass
  GetBookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.GetBookRequest").msgclass
  CreateBookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.CreateBookRequest").msgclass
  CreateAuthorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.CreateAuthorRequest").msgclass
  BookMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.BookMessage").msgclass
  AuthorMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.AuthorMessage").msgclass
  BookResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.BookResponse").msgclass
  AuthorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bookshelf.AuthorResponse").msgclass
end
